CREATE TABLE [dbo].[DEVICE_DATA](
	[DEVICE_DATA_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_DEVICE_DATA] PRIMARY KEY CLUSTERED 
(
	[DEVICE_DATA_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_DATA_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_DATA_DETAILS](
	[DEVICE_DATA_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[DEVICE_DATA_KEY] [uniqueidentifier] NOT NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[DEVICE_KEY] [uniqueidentifier] NOT NULL,
	[TRANSACTION_TIMESTAMP] [datetime] NOT NULL,
	[TRANSACTION_KEY] [uniqueidentifier] NOT NULL,
	[TEMPERATURE_VALUE_01] [decimal](18, 2) NOT NULL,
	[CONTROLLER_KEY] [uniqueidentifier] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DEVICE_DATA_DETAILS_1] PRIMARY KEY CLUSTERED 
(
	[DEVICE_DATA_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_DATA_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_DATA_STATUS](
	[ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[ICON_CSS] [nvarchar](50) NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEVICE_DATA_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
