
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[AspNetClients]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetClients](
	[Id] [nvarchar](50) NOT NULL,
	[Secret] [nvarchar](50) NULL,
	[Name] [nvarchar](100) NULL,
	[ApplicationType] [int] NULL,
	[Active] [bit] NULL,
	[RefreshTokenLifeTime] [int] NULL,
	[AllowedOrigin] [nvarchar](100) NULL,
	[PasswordResetBaseUrl] [nvarchar](100) NULL,
	[CompanyName] [nvarchar](100) NULL,
	[AuthServerEmailUserName] [nvarchar](100) NULL,
	[AuthServerEmailPassword] [nvarchar](100) NULL,
	[AuthServerSmtpServer] [nvarchar](100) NULL,
	[AuthServerSmtpPort] [nvarchar](10) NULL,
	[AuthServerFromAddress] [nvarchar](100) NULL,
	[WelcomeEmailTemplate] [nvarchar](max) NULL,
	[ForgottenPasswordTemplate] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[AspNetRefreshTokens]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRefreshTokens](
	[Id] [nvarchar](50) NOT NULL,
	[ClientId] [nvarchar](50) NULL,
	[IssuedUtc] [datetime] NULL,
	[ExpiresUtc] [datetime] NULL,
	[ApplicationType] [int] NULL,
	[ProtectedTicket] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoles](
	[Id] [nvarchar](128) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](128) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](128) NOT NULL,
	[ProviderKey] [nvarchar](128) NOT NULL,
	[UserId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserRoles](
	[UserId] [nvarchar](128) NOT NULL,
	[RoleId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](128) NOT NULL,
	[Email] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEndDateUtc] [datetime] NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE](
	[DEVICE_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_DEVICE] PRIMARY KEY CLUSTERED 
(
	[DEVICE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_DATA]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_DATA](
	[DEVICE_DATA_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_DEVICE_DATA] PRIMARY KEY CLUSTERED 
(
	[DEVICE_DATA_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_DATA_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_DATA_DETAILS](
	[DEVICE_DATA_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[DEVICE_DATA_KEY] [uniqueidentifier] NOT NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[DEVICE_KEY] [uniqueidentifier] NOT NULL,
	[TRANSACTION_TIMESTAMP] [datetime] NOT NULL,
	[TRANSACTION_KEY] [uniqueidentifier] NOT NULL,
	[TEMPERATURE_VALUE_01] [decimal](18, 2) NOT NULL,
	[CONTROLLER_KEY] [uniqueidentifier] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DEVICE_DATA_DETAILS_1] PRIMARY KEY CLUSTERED 
(
	[DEVICE_DATA_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_DATA_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_DATA_STATUS](
	[ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[ICON_CSS] [nvarchar](50) NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEVICE_DATA_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_DETAILS](
	[DEVICE_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[DEVICE_KEY] [uniqueidentifier] NOT NULL,
	[DEVICE_NAME] [nvarchar](50) NULL,
	[DEVICE_CODE] [nvarchar](50) NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEVICE_DETAILS] PRIMARY KEY CLUSTERED 
(
	[DEVICE_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DEVICE_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_STATUS](
	[ID] [int] NOT NULL,
	[ISACTIVE] [int] NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
	[ICON_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEVICE_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ENTITY]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENTITY](
	[ENTITY_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_ENTITY] PRIMARY KEY CLUSTERED 
(
	[ENTITY_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ENTITY_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENTITY_DETAILS](
	[ENTITY_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[ENTITY_KEY] [uniqueidentifier] NOT NULL,
	[ENTITY_PARENT_NAME] [nvarchar](50) NULL,
	[ENTITY_NAME] [nvarchar](50) NULL,
	[BUTTON_1_ICON_1] [nvarchar](50) NULL,
	[BUTTON_1_TEXT_1] [nvarchar](50) NULL,
	[HEADER_H1] [nvarchar](50) NULL,
	[HEADER_H2] [nvarchar](50) NULL,
	[HEADER_H3] [nvarchar](50) NULL,
	[ADD_ENABLED] [bit] NULL,
	[EDIT_ENABLED] [bit] NULL,
	[DELETE_ENABLED] [bit] NULL,
	[SEARCH_ALL_ENABLED] [bit] NULL,
	[SEARCH_PROPERTY_1] [nvarchar](50) NULL,
	[SEARCH_PROPERTY_2] [nvarchar](50) NULL,
	[SEARCH_PROPERTY_3] [nvarchar](50) NULL,
	[SHOW_ALL_STATUS_FILTER] [bit] NULL,
	[DEFAULT_STATUS_ID] [nvarchar](50) NULL,
	[DEFAULT_SORT_PROPERTY] [nvarchar](50) NULL,
	[SORT_ORDER] [int] NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NULL,
 CONSTRAINT [PK_ENTITY_DETAILS_1] PRIMARY KEY CLUSTERED 
(
	[ENTITY_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ENTITY_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENTITY_STATUS](
	[ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
	[ICON_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_ENTITY_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LOCATION]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCATION](
	[LOCATION_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_LOCATION] PRIMARY KEY CLUSTERED 
(
	[LOCATION_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LOCATION_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCATION_DETAILS](
	[LOCATION_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[LOCATION_KEY] [uniqueidentifier] NOT NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NULL,
 CONSTRAINT [PK_LOCATION_DETAILS] PRIMARY KEY CLUSTERED 
(
	[LOCATION_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LOCATION_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCATION_STATUS](
	[ID] [int] NOT NULL,
	[ISACTIVE] [int] NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
	[ICON_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_LOCATION_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[NOTIFICATION]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION](
	[NOTIFICATION_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[NOTIFICATION_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[NOTIFICATION_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION_DETAILS](
	[NOTIFICATION_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[NOTIFICATION_KEY] [uniqueidentifier] NOT NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NULL,
 CONSTRAINT [PK_NOTIFICATION_DETAILS] PRIMARY KEY CLUSTERED 
(
	[NOTIFICATION_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[NOTIFICATION_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION_STATUS](
	[ID] [int] NOT NULL,
	[ISACTIVE] [int] NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
	[ICON_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_NOTIFICATION_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PERSON]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSON](
	[PERSON_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_PERSON] PRIMARY KEY CLUSTERED 
(
	[PERSON_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PERSON_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSON_DETAILS](
	[PERSON_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[PERSON_KEY] [uniqueidentifier] NOT NULL,
	[FIRST_NAME] [nvarchar](50) NULL,
	[LAST_NAME] [nvarchar](50) NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NULL,
 CONSTRAINT [PK_PERSON_DETAILS] PRIMARY KEY CLUSTERED 
(
	[PERSON_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PERSON_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSON_STATUS](
	[ID] [int] NOT NULL,
	[ISACTIVE] [int] NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
	[ICON_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_PERSON_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THRESHOLD]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THRESHOLD](
	[THRESHOLD_KEY] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_THRESHOLD] PRIMARY KEY CLUSTERED 
(
	[THRESHOLD_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THRESHOLD_DETAILS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THRESHOLD_DETAILS](
	[THRESHOLD_DETAILS_KEY] [uniqueidentifier] NOT NULL,
	[THRESHOLD_KEY] [uniqueidentifier] NOT NULL,
	[RECORD_INDEX] [int] NOT NULL,
	[STATUS_ID] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[IS_ACTIVE_RECORD] [bit] NOT NULL,
	[DEACTIVATED_DATE] [datetime] NULL,
	[DEACTIVATED_BY] [nvarchar](50) NULL,
	[SYSTEM_KEY] [nvarchar](50) NULL,
 CONSTRAINT [PK_THRESHOLD_DETAILS] PRIMARY KEY CLUSTERED 
(
	[THRESHOLD_DETAILS_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THRESHOLD_STATUS]    Script Date: 2015-08-12 07:18:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THRESHOLD_STATUS](
	[ID] [int] NOT NULL,
	[ISACTIVE] [int] NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[ICON_CSS] [nvarchar](50) NULL,
	[COLOUR_CSS] [nvarchar](50) NULL,
 CONSTRAINT [PK_THRESHOLD_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[AspNetClients] ADD  DEFAULT ((0)) FOR [Active]
GO
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[DEVICE_DATA_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_DEVICE_DATA_DETAILS_DEVICE] FOREIGN KEY([DEVICE_KEY])
REFERENCES [dbo].[DEVICE] ([DEVICE_KEY])
GO
ALTER TABLE [dbo].[DEVICE_DATA_DETAILS] CHECK CONSTRAINT [FK_DEVICE_DATA_DETAILS_DEVICE]
GO
ALTER TABLE [dbo].[DEVICE_DATA_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_DEVICE_DATA_DETAILS_DEVICE_DATA] FOREIGN KEY([DEVICE_DATA_KEY])
REFERENCES [dbo].[DEVICE_DATA] ([DEVICE_DATA_KEY])
GO
ALTER TABLE [dbo].[DEVICE_DATA_DETAILS] CHECK CONSTRAINT [FK_DEVICE_DATA_DETAILS_DEVICE_DATA]
GO
ALTER TABLE [dbo].[DEVICE_DATA_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_DEVICE_DATA_DETAILS_DEVICE_DATA_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[DEVICE_DATA_STATUS] ([ID])
GO
ALTER TABLE [dbo].[DEVICE_DATA_DETAILS] CHECK CONSTRAINT [FK_DEVICE_DATA_DETAILS_DEVICE_DATA_STATUS]
GO
ALTER TABLE [dbo].[DEVICE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_DEVICE_DETAILS_DEVICE] FOREIGN KEY([DEVICE_KEY])
REFERENCES [dbo].[DEVICE] ([DEVICE_KEY])
GO
ALTER TABLE [dbo].[DEVICE_DETAILS] CHECK CONSTRAINT [FK_DEVICE_DETAILS_DEVICE]
GO
ALTER TABLE [dbo].[DEVICE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_DEVICE_DETAILS_DEVICE_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[DEVICE_STATUS] ([ID])
GO
ALTER TABLE [dbo].[DEVICE_DETAILS] CHECK CONSTRAINT [FK_DEVICE_DETAILS_DEVICE_STATUS]
GO
ALTER TABLE [dbo].[ENTITY_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ENTITY_DETAILS_ENTITY] FOREIGN KEY([ENTITY_KEY])
REFERENCES [dbo].[ENTITY] ([ENTITY_KEY])
GO
ALTER TABLE [dbo].[ENTITY_DETAILS] CHECK CONSTRAINT [FK_ENTITY_DETAILS_ENTITY]
GO
ALTER TABLE [dbo].[ENTITY_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ENTITY_DETAILS_ENTITY_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[ENTITY_STATUS] ([ID])
GO
ALTER TABLE [dbo].[ENTITY_DETAILS] CHECK CONSTRAINT [FK_ENTITY_DETAILS_ENTITY_STATUS]
GO
ALTER TABLE [dbo].[LOCATION_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_LOCATION_DETAILS_LOCATION] FOREIGN KEY([LOCATION_KEY])
REFERENCES [dbo].[LOCATION] ([LOCATION_KEY])
GO
ALTER TABLE [dbo].[LOCATION_DETAILS] CHECK CONSTRAINT [FK_LOCATION_DETAILS_LOCATION]
GO
ALTER TABLE [dbo].[LOCATION_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_LOCATION_DETAILS_LOCATION_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[LOCATION_STATUS] ([ID])
GO
ALTER TABLE [dbo].[LOCATION_DETAILS] CHECK CONSTRAINT [FK_LOCATION_DETAILS_LOCATION_STATUS]
GO
ALTER TABLE [dbo].[NOTIFICATION_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_NOTIFICATION_DETAILS_NOTIFICATION] FOREIGN KEY([NOTIFICATION_KEY])
REFERENCES [dbo].[NOTIFICATION] ([NOTIFICATION_KEY])
GO
ALTER TABLE [dbo].[NOTIFICATION_DETAILS] CHECK CONSTRAINT [FK_NOTIFICATION_DETAILS_NOTIFICATION]
GO
ALTER TABLE [dbo].[NOTIFICATION_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_NOTIFICATION_DETAILS_NOTIFICATION_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[NOTIFICATION_STATUS] ([ID])
GO
ALTER TABLE [dbo].[NOTIFICATION_DETAILS] CHECK CONSTRAINT [FK_NOTIFICATION_DETAILS_NOTIFICATION_STATUS]
GO
ALTER TABLE [dbo].[PERSON_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_DETAILS_PERSON] FOREIGN KEY([PERSON_KEY])
REFERENCES [dbo].[PERSON] ([PERSON_KEY])
GO
ALTER TABLE [dbo].[PERSON_DETAILS] CHECK CONSTRAINT [FK_PERSON_DETAILS_PERSON]
GO
ALTER TABLE [dbo].[PERSON_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_DETAILS_PERSON_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[PERSON_STATUS] ([ID])
GO
ALTER TABLE [dbo].[PERSON_DETAILS] CHECK CONSTRAINT [FK_PERSON_DETAILS_PERSON_STATUS]
GO
ALTER TABLE [dbo].[THRESHOLD_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_THRESHOLD_DETAILS_THRESHOLD] FOREIGN KEY([THRESHOLD_KEY])
REFERENCES [dbo].[THRESHOLD] ([THRESHOLD_KEY])
GO
ALTER TABLE [dbo].[THRESHOLD_DETAILS] CHECK CONSTRAINT [FK_THRESHOLD_DETAILS_THRESHOLD]
GO
ALTER TABLE [dbo].[THRESHOLD_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_THRESHOLD_DETAILS_THRESHOLD_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[THRESHOLD_STATUS] ([ID])
GO
ALTER TABLE [dbo].[THRESHOLD_DETAILS] CHECK CONSTRAINT [FK_THRESHOLD_DETAILS_THRESHOLD_STATUS]
GO
